### ISSUE TITLE
Problem z id-jem

### ISSUE THREAD

**Issue by tjasabajc** [tjasabajc/Recepti#3]
https://github.com/tjasabajc/Recepti/blob/e8cfeaf4654d2282a17683aa86d71c0b8515e58a/projekt.py#L21

Problem je sledeč. Ko poženeš projekt.py, klikneš na glavni strani na Recepti v meniju zgoraj. (Prvi problem je, da potem spletna stran ni več "lepa", ampak to lahko tudi pustimo zaenkrat.) Potem pa lahko klikneš na enega od receptov, pri tem se kliče get('/recept/id') (kot se vidi zgoraj v 21. vrstici). In tu ne znava tega id dobit noter v funkcijo recept(), kjer bi potem s pomočjo tega id iz baze dobila podatke o tem konkretnem receptu.

Upam, da je razumljivo. Hvala za pomoč!

**Comment by jaanos** [comment]
Spremenljivko dobita kot parameter funkcije `recept`, ki jo torej definirajta kot `def recept(id):`.

Mimogrede, pri metodi `execute` je podatke vedno treba podati v seznamu ali naboru - tudi, če imata en sam podatek. Tako namesto samo `id` pišita `[id]`.
