### ISSUE TITLE
Problem s prijavo in slikami

### ISSUE THREAD

**Issue by tjasabajc** [tjasabajc/Recepti#4]
https://github.com/tjasabajc/Recepti/blob/d0cb348d51447d8dc71e1c6f5928a993d25d5a39/projekt.py#L17

Imava težavo s prijavo uporabnika. Ko se uporabnik prijavi s (pravilnim) imenom in geslom, nekje nastaviva `prijavljen=True` (takrat se recimo Prijava spremeni v Odjavo). Ampak potem se spremeni nazaj v `prijavljen=False,` karkoli klikneš. Kje naj bo ta spremenljivka `prijavljen`, da bo ostala `True` ves čas, doker je nekdo prijavljen?

Druga težava so slike (to je manj pomembno, ampak bi vseeno rada rešila). Do slik sva poskušala dostopati na različne načine, pa še zmeraj ne dela. Trenutno je `<img src="/pica.jpg">.`

Hvala za pomoč!

**Comment by jaanos** [comment]
Spremenljivke, ki so vezane na uporabnika, se spravi v piškotke (*cookies*). Za delo s piškotki imata na voljo funkcije `request.get_cookie`, `response.set_cookie` in `response.delete_cookie`. Za primer uporabe si poglejta [Fakebook](https://github.com/andrejbauer/fakebook/blob/master/fakebook.py).

Slike imata v mapi `static/images` - za statične datoteke pa poskrbita tukaj:

https://github.com/tjasabajc/Recepti/blob/d0cb348d51447d8dc71e1c6f5928a993d25d5a39/projekt.py#L19-L21

Za podano sliko torej navedeta pot `/static/images/pica.jpg`.
